# Generated by Django 5.2.15 on 2026-06-24 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_sell_products', 'Can Sell Products')]},
        ),
    ]
